server:
  port: 10000

spring:
  application:
    name: api-gateway # 应用名称
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
#  routes:
#    user-service: # 这里是路由id，随意写
#      path: /account-service/** # 这里是映射路径
#      url: http://127.0.0.1:8081 # 映射路径对应的实际url地址    
#      serviceId: account-service # 指定服务名称
#     account-service: /account-service/**  #默认配置，不配也有
  ignored-services:  #不提供外界调用的服务，忽略掉默认配置
    - account-service
