#yaml方式属性配置 会和 properties方式取并集、重名以properties为准
server:
  port: 8082
#jdbc:
#  driverClass: com.mysql.jdbc.Driver
#  jdbcUrl: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
#  user: root
#  password: 123456
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
        
  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      
    show-sql: true
  application:
    name: account-service # 应用名称
    
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka #,http://127.0.0.1:10010/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30